import { describe, expect, it } from 'vitest';

import { borders, highContrastPalette, layout, palette, radii, shadows, spacing, type Palette } from '@/ui/tokens';

import { makeStyles } from './catalog.styles';

/**
 * B-M9 byte-identity proof for the catalog sheet. `expected(p)` is an independent
 * transcription of the original static sheet minus the text color/role that moved
 * to `AppText` (the fixed caption sizes stay). Base palette = default prefs →
 * byte-identical; high-contrast palette → every themed prop threads the argument.
 */
function expected(p: Palette) {
  return {
    screen: { backgroundColor: p.wallCream, flex: 1, paddingHorizontal: layout.screenPadX },
    content: { gap: spacing.md, paddingTop: spacing.md },

    // PROG-1 "Shelf Growth" card (replaces the plain % bar with a filling shelf).
    summary: { gap: spacing.sm },
    completionRow: { alignItems: 'baseline', flexDirection: 'row', gap: spacing.sm },
    statsGrid: { flexDirection: 'row', justifyContent: 'space-between' },
    stat: { alignItems: 'center', flex: 1, gap: spacing.xxs },
    statLabel: { fontSize: 10 },
    statValueRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.xxs },

    growthTop: { alignItems: 'center', flexDirection: 'row', gap: spacing.md },
    growthHeadline: { flex: 1, gap: spacing.xxs },
    combosChip: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: p.parchment,
      borderRadius: radii.pill,
      flexDirection: 'row',
      gap: spacing.xxs,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
    },

    miniShelf: {
      backgroundColor: p.shelfWood,
      borderColor: p.woodDark,
      borderRadius: radii.sm,
      borderWidth: borders.regular,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xxs,
      padding: spacing.xs,
      width: 93,
    },
    miniCell: { borderRadius: radii.xs, height: 10, width: 10 },
    miniCellEmpty: { backgroundColor: p.woodInset },
    miniCellHeirloom: { backgroundColor: p.coinGold },
    miniCellRare: { backgroundColor: p.goldDeep },
    miniCellFine: { backgroundColor: p.sunlight },
    miniCellCommon: { backgroundColor: p.parchmentEdge },

    nextStrip: {
      alignItems: 'center',
      backgroundColor: p.parchment,
      borderColor: p.parchmentEdge,
      borderRadius: radii.md,
      borderWidth: borders.hairline,
      flexDirection: 'row',
      gap: spacing.sm,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
    },
    nextThumbCircle: {
      alignItems: 'center',
      backgroundColor: p.wallCream,
      borderColor: p.parchmentEdge,
      borderRadius: radii.pill,
      borderWidth: borders.hairline,
      height: 36,
      justifyContent: 'center',
      width: 36,
    },
    nextThumb: { height: 26, width: 26 },
    nextThumbDot: { backgroundColor: p.inkFaint, borderRadius: radii.pill, height: 20, width: 20 },
    nextText: { flex: 1, gap: spacing.xxs },
    nextTick: { alignItems: 'flex-end', gap: spacing.xxs, width: 52 },
    nextTickTrack: {
      backgroundColor: p.parchmentEdge,
      borderRadius: radii.pill,
      height: 4,
      overflow: 'hidden',
      width: '100%',
    },
    nextTickFill: { backgroundColor: p.accentTeal, borderRadius: radii.pill, height: 4 },
    nextTickText: { fontSize: 12, letterSpacing: 0 },

    segment: {
      backgroundColor: p.parchment,
      borderRadius: radii.pill,
      flexDirection: 'row',
      padding: spacing.xs,
      position: 'relative',
    },
    segmentPill: {
      backgroundColor: p.creamBright,
      borderRadius: radii.pill,
      bottom: spacing.xs,
      left: spacing.xs,
      position: 'absolute',
      top: spacing.xs,
      ...shadows.float,
    },
    segmentBtn: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: 44, zIndex: 1 },
    segmentLabel: { letterSpacing: 0.6 },

    legendChips: { flexDirection: 'row', gap: spacing.xs },
    legendChip: {
      alignItems: 'center',
      backgroundColor: p.creamBright,
      borderColor: p.parchmentEdge,
      borderRadius: radii.sm,
      borderTopWidth: borders.strong,
      borderWidth: borders.hairline,
      flex: 1,
      gap: spacing.xxs,
      paddingHorizontal: spacing.xxs,
      paddingVertical: spacing.xs,
    },
    legendAccentHeirloom: { borderTopColor: p.coinGold },
    legendAccentRare: { borderTopColor: p.goldDeep },
    legendAccentFine: { borderTopColor: p.sunlight },
    legendAccentCommon: { borderTopColor: p.parchmentEdge },
    legendChipName: { fontSize: 10, letterSpacing: 0.4, textAlign: 'center' },
    legendChipCountRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.xxs },
    legendChipCount: { fontSize: 13, letterSpacing: 0 },

    band: { gap: spacing.sm },

    grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
    stamp: {
      alignItems: 'center',
      borderRadius: radii.md,
      borderWidth: 1,
      gap: spacing.xxs,
      padding: spacing.xs,
      width: '22%',
    },
    stampFound: {
      backgroundColor: p.creamBright,
      borderColor: p.goldDeep,
      ...shadows.card,
    },
    stampFine: {
      backgroundColor: `${p.sunlight}59`,
      borderColor: p.goldDeep,
      borderWidth: borders.regular,
      ...shadows.card,
    },
    stampRare: {
      backgroundColor: p.creamBright,
      borderColor: p.goldDeep,
      borderWidth: borders.strong,
      ...shadows.card,
    },
    stampHeirloom: {
      backgroundColor: `${p.sunlight}8C`,
      borderColor: p.goldDeep,
      borderWidth: borders.strong,
      ...shadows.lifted,
    },
    stampInnerRing: {
      borderColor: p.coinGold,
      borderRadius: radii.sm,
      borderWidth: 1,
      bottom: spacing.xxs,
      left: spacing.xxs,
      position: 'absolute',
      right: spacing.xxs,
      top: spacing.xxs,
    },
    stampCrown: {
      alignItems: 'center',
      backgroundColor: p.creamBright,
      borderColor: p.goldDeep,
      borderRadius: radii.pill,
      borderWidth: 1.5,
      height: 20,
      justifyContent: 'center',
      position: 'absolute',
      right: spacing.xxs,
      top: spacing.xxs,
      width: 20,
      zIndex: 2,
    },
    stampLocked: { backgroundColor: p.parchment, borderColor: p.parchmentEdge, opacity: 0.85 },
    stampArt: {
      alignItems: 'center',
      aspectRatio: 1,
      backgroundColor: p.wallCream,
      borderRadius: radii.sm,
      justifyContent: 'center',
      padding: spacing.sm,
      width: '100%',
    },
    stampSprite: { height: '100%', width: '100%' },
    stampMystery: {
      alignItems: 'center',
      aspectRatio: 1,
      backgroundColor: p.parchment,
      borderColor: p.parchmentEdge,
      borderRadius: radii.sm,
      borderWidth: 1.5,
      justifyContent: 'center',
      width: '100%',
    },
    stampName: { fontSize: 9, letterSpacing: 0, textAlign: 'center' },
    silhouette: { tintColor: p.inkFaint },
    stampSilhouetteBox: {
      aspectRatio: 1,
      backgroundColor: p.inkFaint,
      borderRadius: radii.sm,
      width: '100%',
    },
    stampLockHint: {
      fontSize: 9,
      letterSpacing: 0,
      textAlign: 'center',
    },
    stampProgress: { alignItems: 'center', gap: spacing.xxs, width: '100%' },
    stampProgressTrack: {
      backgroundColor: p.parchmentEdge,
      borderRadius: radii.pill,
      height: 4,
      overflow: 'hidden',
      width: '100%',
    },
    stampProgressFill: { backgroundColor: p.goldDeep, borderRadius: radii.pill, height: 4 },
    stampProgressText: { fontSize: 9, letterSpacing: 0 },
    revealRing: {
      borderColor: p.goldDeep,
      borderRadius: radii.md,
      borderWidth: 2,
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },

    comboList: { gap: spacing.sm },
    combo: {
      alignItems: 'center',
      borderRadius: radii.md,
      borderWidth: 1,
      flexDirection: 'row',
      gap: spacing.md,
      padding: spacing.md,
    },
    comboFound: { backgroundColor: p.creamBright, borderColor: p.goldDeep },
    comboLocked: { backgroundColor: p.parchment, borderColor: p.parchmentEdge, opacity: 0.7 },
    newBadge: {
      backgroundColor: p.goldDeep,
      borderRadius: radii.pill,
      paddingHorizontal: spacing.xs,
      paddingVertical: 1,
    },
    newBadgeText: { fontSize: 9, letterSpacing: 0.4 },
    comboText: { flex: 1 },
    comboName: { fontSize: 15 },
    comboCount: { fontSize: 13, fontWeight: '700' },
    comboHint: { fontSize: 12 },
    comboContext: { fontSize: 11, letterSpacing: 0 },

    comboShelf: { gap: spacing.lg },
    shelfBed: {
      backgroundColor: p.shelfWood,
      borderColor: p.woodDark,
      borderRadius: radii.md,
      borderWidth: borders.strong,
      paddingHorizontal: spacing.md,
      paddingTop: spacing.md,
      ...shadows.card,
    },
    shelfMedalRow: { flexDirection: 'row' },
    shelfCell: { alignItems: 'center', flex: 1, gap: spacing.xs, paddingHorizontal: spacing.xxs },
    shelfPlank: {
      backgroundColor: p.woodLight,
      borderBottomColor: p.woodDark,
      borderBottomWidth: borders.strong,
      borderRadius: radii.xs,
      height: 12,
      marginTop: spacing.md,
    },
    medalCountChip: {
      alignItems: 'center',
      backgroundColor: p.coinGold,
      borderColor: p.goldDeep,
      borderRadius: radii.pill,
      borderWidth: borders.regular,
      marginTop: -spacing.lg,
      paddingHorizontal: spacing.sm,
      paddingVertical: 2,
      zIndex: 2,
    },
    medalCountText: { fontSize: 12, letterSpacing: 0 },
    medalStack: { alignItems: 'center', justifyContent: 'center' },
    medalName: { fontSize: 14, lineHeight: 18, minHeight: 18, textAlign: 'center' },
    medalLockHint: { fontSize: 10, lineHeight: 14, textAlign: 'center' },
    medalRevealRing: {
      borderColor: p.goldDeep,
      borderRadius: radii.pill,
      borderWidth: borders.strong,
      height: 108,
      position: 'absolute',
      width: 108,
    },
    medalGlint: {
      backgroundColor: p.creamBright,
      borderRadius: radii.xs,
      height: 150,
      opacity: 0.5,
      position: 'absolute',
      width: 22,
    },
    medalNewBadge: { position: 'absolute', right: 0, top: -spacing.xs, zIndex: 3 },

    comboModalCard: {
      alignItems: 'center',
      backgroundColor: p.creamBright,
      borderColor: p.goldDeep,
      borderRadius: radii.lg,
      borderWidth: borders.strong,
      gap: spacing.md,
      maxWidth: 360,
      padding: spacing.xl,
      width: '100%',
      ...shadows.lifted,
    },
    comboModalUnlock: { textAlign: 'center' },
    comboModalCount: { fontSize: 13, letterSpacing: 0 },

    recipe: { alignItems: 'center', gap: spacing.xxs, paddingVertical: spacing.xxs },
    recipeRow: { flexDirection: 'row', gap: spacing.xxs, justifyContent: 'center' },
    recipeWell: {
      alignItems: 'center',
      backgroundColor: p.woodInset,
      borderColor: p.woodDark,
      borderRadius: radii.sm,
      borderWidth: borders.regular,
      height: 52,
      justifyContent: 'center',
      width: 52,
    },
    recipeWellEmpty: { backgroundColor: p.woodDark, opacity: 0.45 },
    recipeWellCenter: { borderColor: p.goldDeep, borderWidth: borders.strong },
    recipeTagChip: {
      alignItems: 'center',
      backgroundColor: p.creamBright,
      borderColor: p.parchmentEdge,
      borderRadius: radii.pill,
      borderWidth: 1,
      height: 18,
      justifyContent: 'center',
      position: 'absolute',
      right: -spacing.xs,
      top: -spacing.xs,
      width: 18,
      zIndex: 2,
    },

    modalScrim: {
      alignItems: 'center',
      backgroundColor: p.scrim,
      flex: 1,
      justifyContent: 'center',
      padding: spacing.xl,
    },
    modalCard: {
      alignItems: 'center',
      borderRadius: radii.lg,
      borderWidth: borders.hairline,
      gap: spacing.md,
      maxWidth: 360,
      padding: spacing.xl,
      width: '100%',
    },
    modalClose: {
      alignItems: 'center',
      backgroundColor: p.parchment,
      borderColor: p.parchmentEdge,
      borderRadius: radii.pill,
      borderWidth: 1,
      height: 32,
      justifyContent: 'center',
      position: 'absolute',
      right: spacing.md,
      top: spacing.md,
      width: 32,
      zIndex: 3,
    },
    modalSpriteBed: {
      alignItems: 'center',
      aspectRatio: 1,
      backgroundColor: p.wallCream,
      borderColor: p.goldDeep,
      borderRadius: radii.lg,
      borderWidth: borders.regular,
      justifyContent: 'center',
      width: 168,
    },
    modalSpriteRing: {
      borderColor: `${p.goldDeep}55`,
      borderRadius: radii.pill,
      borderWidth: 1.5,
      height: 150,
      position: 'absolute',
      width: 150,
    },
    modalSpriteHalo: {
      backgroundColor: `${p.sunlight}66`,
      borderRadius: radii.pill,
      height: 128,
      position: 'absolute',
      width: 128,
    },
    modalSprite: { height: 128, width: 128 },
    modalCrown: {
      alignItems: 'center',
      backgroundColor: p.creamBright,
      borderColor: p.goldDeep,
      borderRadius: radii.pill,
      borderWidth: 2,
      height: 34,
      justifyContent: 'center',
      position: 'absolute',
      right: -spacing.xs,
      top: -spacing.xs,
      width: 34,
      zIndex: 2,
    },
    modalName: { textAlign: 'center' },
    modalBandChip: {
      backgroundColor: p.parchment,
      borderColor: p.goldDeep,
      borderRadius: radii.pill,
      borderWidth: 1,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
    },
    modalBandChipText: { letterSpacing: 1.2 },
    modalTags: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, justifyContent: 'center' },
    modalTagChip: {
      alignItems: 'center',
      backgroundColor: p.creamBright,
      borderColor: p.parchmentEdge,
      borderRadius: radii.pill,
      borderWidth: 1,
      flexDirection: 'row',
      gap: spacing.xxs,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
    },
    modalTagText: { letterSpacing: 0 },
    modalValueRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.xs },
    modalCoinDot: {
      backgroundColor: p.coinGold,
      borderColor: p.goldDeep,
      borderRadius: radii.pill,
      borderWidth: borders.regular,
      height: 16,
      width: 16,
    },
    modalDivider: { alignSelf: 'stretch', backgroundColor: p.parchmentEdge, height: 1 },
    modalSection: { alignSelf: 'stretch', gap: spacing.sm },
    modalRuleList: { gap: spacing.xs },
    modalRule: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.sm },
    modalRuleBullet: {
      backgroundColor: p.goldDeep,
      borderRadius: radii.pill,
      height: 6,
      marginTop: 7,
      width: 6,
    },
    modalRuleText: { flex: 1 },
    modalShine: {
      borderColor: p.goldDeep,
      borderRadius: radii.lg,
      borderWidth: 2,
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
  };
}

describe('catalog.tsx themed styles', () => {
  it('is byte-identical at default prefs (base palette)', () => {
    expect(makeStyles(palette)).toEqual(expected(palette));
  });

  it('threads the palette argument under high contrast (no static leak)', () => {
    expect(makeStyles(highContrastPalette)).toEqual(expected(highContrastPalette));
  });
});
