import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import type { Action, GameState } from '../src/contracts';
import { GameStateSchema } from '../src/contracts';
import { loadCombos, loadItemTable } from '../src/items';
import { dispatch } from '../src/sim/engine';
import { makeState } from '../src/sim/testkit';

const deps = { table: loadItemTable(), combos: loadCombos() };
const outputPath = resolve(process.cwd(), 'fixtures/m2-arrange-sticky.json');

const startingState = makeState(
  [
    { slot: { row: 0, col: 0 }, itemId: 'honey-jar' },
    { slot: { row: 0, col: 1 }, itemId: 'cheese-wheel' },
    { slot: { row: 1, col: 1 }, itemId: 'wine-bottle' },
  ],
  {
    runId: 'run-m2-arrange-sticky',
    seed: 'm2-arrange-sticky',
    phase: 'arrange',
    day: 1,
    currentOffers: [],
  },
);

const actions: Action[] = [
  { type: 'openShop' },
  { type: 'draftItem', offerIndex: 0 },
  { type: 'placeItem', slot: { row: 2, col: 3 } },
];

const gameState = actions.reduce<GameState>(
  (state, action) => dispatch(state, action, deps),
  startingState,
);

GameStateSchema.parse(gameState);

const stickyItems = gameState.shelf.slots.filter((slot) => slot.item?.state.sticky);
if (gameState.phase !== 'arrange' || gameState.heldItem !== null || stickyItems.length === 0) {
  throw new Error('Generated sticky fixture does not satisfy arrange-phase sticky requirements.');
}

const fixture = {
  fixtureId: 'm2-arrange-sticky',
  title: 'Arrange Phase Sticky Item',
  laneBUse: 'Retire the hand-authored drag mock with an engine-generated arrange state containing a sticky item and empty move targets.',
  notes: [
    'Generated by Honey Jar scoring in the prior openShop pass; sticky is active from this arrange phase.',
    'The held delivery item has been placed, so normal moveItem dispatches are legal except for sticky items and move economy limits.',
    'This file is intentionally outside fixtures/m0-fixtures.json because FixtureCollectionSchema is frozen to length 6.',
  ],
  sourceActions: actions,
  gameState,
};

writeFileSync(outputPath, `${JSON.stringify(fixture, null, 2)}\n`);
console.log(`Wrote ${outputPath}.`);
